spring:
    application:
      name: remote-controller
      main:
        web_environment: true
server:
  port: 8080
  context-path: /
  context_parameters:
      defaultHtmlEscape: true

mouse:
  pressDelay: 10 #ms used for Thread.sleep(delay)
  maxClicks: 3
screen:
  size:
    width: 1920
    height: 1080
  capture:
    centered: true
    small:
      width: 100
      height: 50